env:
  browser: true
  es2022: true
  node: true
  jest: true  # Добавлено для поддержки Jest

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 2022
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true  
  no-underscore-dangle:
    - error
    - allow:
        - __filename
        - __dirname