env:
  browser: true
  es2022: true
  node: true
  jest: true

extends: airbnb-base

plugins:
  - "@typescript-eslint"
  - "@stylistic"

parserOptions:
  ecmaVersion: 2022
  sourceType: module

ignorePatterns:
  - "fixtures/**"

rules:
  semi: ["error", "never"]
  "@stylistic/semi": "off"
  "arrow-parens": ["error", "as-needed"]
  "@stylistic/arrow-parens": "off"
  "@stylistic/no-multiple-empty-lines": ["error", { max: 1 }]
  "no-console": "off"
  "import/extensions": ["error", "ignorePackages"]
  "import/no-extraneous-dependencies": ["error", { "devDependencies": true }]
  "no-underscore-dangle": ["error", { "allow": ["__filename", "__dirname"] }]