env:
  browser: true
  es2022: true
  node: true
  jest: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 2022
  sourceType: module

ignorePatterns:
  - "fixtures/**"

rules:
  "no-console": "off"
  "import/extensions": ["error", "ignorePackages"]
  "import/no-extraneous-dependencies": [
    "error",
    {
      "devDependencies": true
    }
  ]
  "no-underscore-dangle": [
    "error",
    {
      "allow": ["__filename", "__dirname"]
    }
  ]