name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '11.3.0'
    - run: npm install
    - run: make lint
    - run: npm test -- --coverage
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}